#!/bin/bash
#
# 1. batch blastn to local copy of nt database 
#
for file in *.fa
do
{
echo "blasting file $file"
blastn -db /Applications/1_genomics/ncbi-blast-2.2.30+/db/nt -query $file -out ./Out$file.txt -num_threads 3
}
done
wait
#
# 2. Batch process and LCA in Megan
#
#
for file in *.fa
do
{
echo "import blastFile='/Users/ferninfm/Desktop/ANTONIA/2_Not_collapsed/blast_v3/Out$file.txt' fastaFile='/Users/ferninfm/Desktop/ANTONIA/2_Not_collapsed/blast_v3/$file' meganFile='/Users/ferninfm/Desktop/ANTONIA/2_Not_collapsed/blast_v3/megan2_$file.rma' minScore=200 topPercent=5 minSupport=1 blastFormat=BlastN">comands.txt
echo "export what=paths file= '/Users/ferninfm/Desktop/ANTONIA/2_Not_collapsed/blast_v3/Taxonomy_$file.txt'">>comands.txt
echo "quit">>comands.txt
echo "">>comands.txt
echo "Processing file $file in Megan"
/Applications/MEGAN/MEGAN.app/Contents/MacOS/JavaApplicationStub -g -E < comands.txt
}
done
#
# 3. Merging of all samples was done manually in megan afterwards
#
#
